(function () {
  'use strict';
  const topics = [
    {s:'physics',sn:'물리학',school:'middle',sc:'중학교',d:'basic',dn:'기초',t:'진자의 길이는 왕복 시간에 어떤 영향을 줄까?',q:'추의 질량은 그대로 두고 줄의 길이만 바꾸면 단진자의 주기는 어떻게 변할까?',c:'주기 운동, 중력, 단진자 주기',time:'30~40분',items:'실, 추, 자, 초시계',mode:'simulation',link:'/simulation/pendulum.html',keys:'진자 길이 주기 역학 중력'},
    {s:'physics',sn:'물리학',school:'high',sc:'고등학교',d:'standard',dn:'보통',t:'진자의 초기 각도와 작은 각도 근사의 한계',q:'초기 각도가 커질수록 측정 주기와 T=2π√(L/g)의 차이는 어떻게 달라질까?',c:'단진자, 작은 각도 근사, 오차율',time:'40~60분',items:'단진자 시뮬레이션, 계산기',mode:'simulation',link:'/simulation/pendulum.html',keys:'진자 각도 근사 주기 오차'},
    {s:'physics',sn:'물리학',school:'high',sc:'고등학교',d:'advanced',dn:'심화',t:'자석의 속도와 유도 기전력의 관계',q:'코일을 통과하는 자석의 속도가 증가하면 최대 유도 기전력은 어떤 관계로 변할까?',c:'자기선속, 패러데이 법칙, 유도 기전력',time:'40~60분',items:'전자기 유도 시뮬레이션, 기록지',mode:'simulation',link:'/simulation/electromagnetic-induction.html',keys:'전자기 유도 자석 속도 코일 패러데이'},
    {s:'physics',sn:'물리학',school:'middle',sc:'중학교',d:'standard',dn:'보통',t:'표면의 재질에 따른 마찰력 비교',q:'같은 물체를 서로 다른 표면에서 끌 때 필요한 힘은 어떻게 달라질까?',c:'마찰력, 힘의 평형, 측정',time:'30~45분',items:'용수철저울, 나무 블록, 천·사포',mode:'experiment',keys:'마찰력 표면 힘 역학'},
    {s:'chemistry',sn:'화학',school:'middle',sc:'중학교',d:'basic',dn:'기초',t:'물의 온도와 고체 용질의 용해 속도',q:'물의 온도가 높을수록 같은 양의 설탕이 녹는 시간은 얼마나 짧아질까?',c:'용해, 입자 운동, 온도',time:'30~40분',items:'비커, 물, 설탕, 온도계, 초시계',mode:'experiment',keys:'용해 온도 설탕 입자'},
    {s:'chemistry',sn:'화학',school:'high',sc:'고등학교',d:'standard',dn:'보통',t:'농도에 따른 산·염기 중화 반응의 온도 변화',q:'같은 부피에서 용액의 농도가 증가하면 중화 반응의 최고 온도는 어떻게 달라질까?',c:'중화 반응, 반응열, 몰 농도',time:'50~70분',items:'묽은 산·염기, 온도계, 보안경',mode:'experiment',keys:'산 염기 중화 농도 반응열'},
    {s:'chemistry',sn:'화학',school:'high',sc:'고등학교',d:'advanced',dn:'심화',t:'촉매가 과산화수소 분해 속도에 미치는 영향',q:'촉매의 양을 바꾸면 일정 시간 동안 발생하는 산소의 부피는 어떻게 달라질까?',c:'반응 속도, 촉매, 기체 발생',time:'60~80분',items:'과산화수소, 촉매, 기체 포집 장치, 보안경',mode:'experiment',keys:'촉매 과산화수소 반응속도 산소'},
    {s:'biology',sn:'생명과학',school:'middle',sc:'중학교',d:'basic',dn:'기초',t:'빛의 세기와 식물의 기체 발생량',q:'수생식물과 광원 사이 거리가 가까워질수록 분당 기포 수는 어떻게 달라질까?',c:'광합성, 빛의 세기, 제한 요인',time:'40~60분',items:'수생식물, 조명, 자, 초시계',mode:'experiment',keys:'광합성 빛 식물 기포'},
    {s:'biology',sn:'생명과학',school:'high',sc:'고등학교',d:'standard',dn:'보통',t:'온도가 효소 활성에 미치는 영향',q:'온도 변화에 따라 카탈레이스 반응 속도는 어떤 최적점을 보일까?',c:'효소, 활성화 에너지, 단백질 변성',time:'50~70분',items:'감자 추출액, 과산화수소, 항온 수조',mode:'experiment',keys:'효소 온도 카탈레이스 단백질'},
    {s:'biology',sn:'생명과학',school:'high',sc:'고등학교',d:'advanced',dn:'심화',t:'표본 면적과 생물 다양성 추정값의 관계',q:'방형구 면적을 늘리면 관찰되는 종수와 다양성 지수는 어떻게 변할까?',c:'생태 조사, 방형구법, 종 다양성',time:'60~90분',items:'줄자, 방형구, 생물 도감, 기록지',mode:'experiment',keys:'생태계 다양성 방형구 종수'},
    {s:'earth',sn:'지구과학',school:'middle',sc:'중학교',d:'standard',dn:'보통',t:'토양 종류에 따른 물의 침투 속도',q:'모래와 점토의 입자 크기 차이는 같은 양의 물이 통과하는 시간에 어떤 영향을 줄까?',c:'토양 입자, 공극, 지하수',time:'40~60분',items:'모래, 점토, 깔때기, 메스실린더',mode:'experiment',keys:'토양 물 침투 모래 점토 지하수'},
    {s:'earth',sn:'지구과학',school:'high',sc:'고등학교',d:'advanced',dn:'심화',t:'도시 표면 재질과 열섬 효과 모형 실험',q:'아스팔트·잔디를 모사한 표면은 같은 빛을 받을 때 온도 상승과 냉각 속도가 어떻게 다를까?',c:'복사 평형, 비열, 도시 열섬',time:'60~80분',items:'검은 판, 흙·잔디 모형, 조명, 온도 센서',mode:'experiment',keys:'도시 열섬 표면 온도 복사 비열'}
  ];
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const grid=document.getElementById('topic-grid'),count=document.getElementById('result-count'),empty=document.getElementById('empty-message');
  const search=document.getElementById('topic-search'),subject=document.getElementById('subject-filter'),school=document.getElementById('school-filter'),difficulty=document.getElementById('difficulty-filter');
  function card(x){const action=x.link?`<a class="btn btn-ghost" href="${x.link}">시뮬레이션 열기</a>`:'';return `<article class="topic-card"><div class="topic-card-head"><span class="subject ${x.s}">${x.sn}</span><div><span class="tag">${x.sc}</span> <span class="tag primary">${x.dn}</span></div></div><h3>${esc(x.t)}</h3><p class="question"><strong>탐구 질문</strong><br>${esc(x.q)}</p><dl class="topic-info"><div><dt>관련 교과 개념</dt><dd>${esc(x.c)}</dd></div><div><dt>예상 소요 시간</dt><dd>${x.time}</dd></div><div><dt>필요한 준비물</dt><dd>${esc(x.items)}</dd></div><div><dt>탐구 방식</dt><dd>${x.mode==='simulation'?'웹 시뮬레이션':'직접 실험'}</dd></div></dl><div class="topic-actions"><span class="${x.link?'available':'unavailable'}">${x.link?'● 시뮬레이션 가능':'● 직접 실험 가능'}</span>${action}</div></article>`}
  function render(){const q=search.value.trim().toLocaleLowerCase('ko-KR');const rows=topics.filter(x=>(subject.value==='all'||x.s===subject.value)&&(school.value==='all'||x.school===school.value)&&(difficulty.value==='all'||x.d===difficulty.value)&&(!q||`${x.t} ${x.q} ${x.c} ${x.keys}`.toLocaleLowerCase('ko-KR').includes(q)));grid.innerHTML=rows.map(card).join('');count.textContent=`${rows.length}개 표시 중`;empty.hidden=rows.length!==0;}
  [search,subject,school,difficulty].forEach(el=>el.addEventListener(el===search?'input':'change',render));render();
})();
